# Generated by Django 5.0 on 2024-02-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLS',
            new_name='URL',
        ),
    ]
