# Generated by Django 5.0 on 2024-02-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
